# Generated by Django 4.2.7 on 2026-01-19 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
        ("rubrics", "0001_initial"),
        ("evaluations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="score",
            options={
                "ordering": ["evaluation", "student", "criterion__order"],
                "verbose_name": "Score",
                "verbose_name_plural": "Scores",
            },
        ),
        migrations.AlterUniqueTogether(
            name="score",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="score",
            name="student",
            field=models.ForeignKey(
                blank=True,
                help_text="Student being scored (null for team-level scores)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scores",
                to="accounts.student",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="score",
            unique_together={("evaluation", "criterion", "student")},
        ),
    ]
