# Generated by Django 4.2.7 on 2026-01-22 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_refactor_to_faculty"),
        ("accounts", "0005_refactor_to_faculty"),
        ("evaluations", "0003_evaluation_judge_signature"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="evaluation",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="faculty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluations",
                to="accounts.faculty",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="evaluation",
            unique_together={("project", "faculty")},
        ),
        migrations.RemoveField(
            model_name="evaluation",
            name="judge",
        ),
    ]
