# Generated by Django 4.2.7 on 2026-01-22 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                help_text="Project supervisor (cannot be a judge for this project)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervised_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
