# Generated by Django 4.2.7 on 2026-01-22 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_refactor_to_faculty"),
        ("projects", "0002_add_supervisor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="supervisor",
        ),
        migrations.CreateModel(
            name="FacultyProjectAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("JUDGE", "Judge"), ("SUPERVISOR", "Supervisor")],
                        help_text="Role of faculty member for this project",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_assignments",
                        to="accounts.faculty",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculty_assignments",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Faculty Project Assignment",
                "verbose_name_plural": "Faculty Project Assignments",
                "ordering": ["-created_at"],
                "unique_together": {("project", "faculty")},
            },
        ),
    ]
