# Generated by Django 4.2.7 on 2026-09-29 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_must_change_password'),
        ('projects', '0003_refactor_to_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField(help_text='Week of the semester, e.g. 1')),
                ('meeting_date', models.DateField(help_text='Date the meeting took place')),
                ('comments', models.TextField(blank=True, help_text="Notes on the team's progress and performance this week")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='projects.project')),
                ('supervisor', models.ForeignKey(blank=True, help_text='Faculty member who recorded this meeting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_reports', to='accounts.faculty')),
            ],
            options={
                'verbose_name': 'Weekly Progress Sheet',
                'verbose_name_plural': 'Weekly Progress Sheets',
                'ordering': ['project', '-week_number'],
                'unique_together': {('project', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excused')], default='PRESENT', max_length=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='projects.weeklyprogress')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_attendance', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Weekly Attendance',
                'verbose_name_plural': 'Weekly Attendance',
                'ordering': ['student__student_id'],
                'unique_together': {('report', 'student')},
            },
        ),
    ]
