# Generated by Django 4.2.7 on 2026-01-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("JUDGE", "Judge"),
                    ("STUDENT", "Student"),
                    ("SUPERVISOR", "Supervisor"),
                ],
                default="STUDENT",
                max_length=10,
            ),
        ),
    ]
