# Generated by Django 4.2.7 on 2026-01-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_add_supervisor_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "faculty_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("department", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Faculty",
                "verbose_name_plural": "Faculty",
                "ordering": ["faculty_id", "user__last_name"],
            },
        ),
        migrations.RemoveField(
            model_name="judge",
            name="user",
        ),
        migrations.RemoveField(
            model_name="supervisor",
            name="user",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("STUDENT", "Student"),
                    ("FACULTY", "Faculty"),
                ],
                default="STUDENT",
                max_length=10,
            ),
        ),
    ]
