# Generated by Django 4.2.7 on 2026-01-22 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0004_refactor_to_faculty"),
        ("accounts", "0005_refactor_to_faculty"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Judge",
        ),
        migrations.DeleteModel(
            name="Supervisor",
        ),
        migrations.AddField(
            model_name="faculty",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faculty_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
