# Generated by Django 4.2.7 on 2026-01-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_refactor_to_faculty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
