# Generated by Django 4.2.7 on 2026-01-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_student_student_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="major",
            field=models.CharField(
                blank=True,
                help_text="Student's major field of study",
                max_length=200,
                null=True,
            ),
        ),
    ]
