# Generated by Django 4.2.7 on 2026-01-27 16:34

from django.db import migrations


def set_default_major(apps, schema_editor):
    """Set all existing students' major to 'CECS'"""
    Student = apps.get_model('accounts', 'Student')
    Student.objects.filter(major__isnull=True).update(major='CECS')
    Student.objects.filter(major='').update(major='CECS')


def reverse_set_default_major(apps, schema_editor):
    """Reverse migration - set major back to None"""
    Student = apps.get_model('accounts', 'Student')
    Student.objects.filter(major='CECS').update(major=None)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_student_major"),
    ]

    operations = [
        migrations.RunPython(set_default_major, reverse_set_default_major),
    ]
