# Generated by Django 4.2.7 on 2026-09-08 13:50

from django.db import migrations, models


def clear_flag_for_existing_users(apps, schema_editor):
    """
    The field defaults to True so every NEW account must set a password.
    Accounts that already existed keep the password they are using.
    """
    User = apps.get_model("accounts", "User")
    User.objects.update(must_change_password=False)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_set_default_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text='Force this user to set a new password the next time they sign in.'),
        ),
        migrations.RunPython(clear_flag_for_existing_users, noop),
    ]
