# Generated by Django 4.2.7 on 2026-01-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rubrics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="criterion",
            name="section_title",
            field=models.CharField(
                blank=True,
                help_text="Section title (e.g., 'Midterm Presentation (Group)') - editable for organizing criteria",
                max_length=200,
                null=True,
            ),
        ),
    ]
